### ISSUE TITLE
I have built EmguCV on Ubuntu 18.04, then what is next step?

### ISSUE THREAD

**Issue by mlstudies** [emgucv/emgucv#150]
I have built EmguCV on Ubuntu 18.04 by running the script /platform/ubuntu/16.04/cmake_configue.sh

I am not sure, but I think the instruction in http://www.emgu.com/wiki/index.php/Download_And_Installation for Ubuntu could be outdated. The above script seems to complete all the build. There is no make file in the root folder. 

Now, I don't know what is next step. There is no "bin" folder in the root folder. There is a "bin" folder in the "/platform/Ubuntu/16.04/build" and it consists of all ".a" files. I cannot find the compiled examples, I cannot find those "dlls", and my program using EmguCV still complains about "DllNotFoundException" occurrs in cvextern. 

![image](https://user-images.githubusercontent.com/40074880/43291043-01b5d2a2-90fe-11e8-8d49-7b4b0bc4f8e5.png)

![image](https://user-images.githubusercontent.com/40074880/43290933-b8175aee-90fd-11e8-9157-b5225c68d847.png)

![image](https://user-images.githubusercontent.com/40074880/43290938-bba3a37a-90fd-11e8-80d8-4c194ffbd28d.png)

**Comment by emgucv** [comment]
Emgu CV have not officially support Ubuntu 18.04 at this moment. The 3.4.1 release tag supports 16.04. 

We will be working on Emgu CV compilation for Ubuntu 18.04 for the 4.0 release.

**Comment by emgucv** [comment]
Fixed with the following commit:
f6e031bdc027f97d4528dce625e8d4d30ba8352f
e94e37196f2d7f797f9c9f46ba8f7e20dfe83f98

**Comment by mlstudies** [comment]
Thanks! Currently on my machine I got a lot file not found errors at the last step. I checked the repo, the Emgu.CV.World indeed does not contain these files.

[```
 99%] Building ../../../../libs/Emgu.CV.World.dll
Microsoft (R) Visual C# Compiler version 2.7.0.62620 (e873e693)
Copyright (C) Microsoft Corporation. All rights reserved.

error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Features2D/Brisk.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Moments.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV.Cuda/Filters/CudaSobelFilter.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/PInvoke/CvType/MDMatch.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Tiff/TiffWriter.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV.Contrib/ImgHash/AverageHash.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/Android/AndroidFileAsset.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Video/FarnebackOpticalFlow.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/DisposableObject.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Features2D/DescriptorMatcher.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/EventArgs.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV.Cuda/GpuMat.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/MomentsGenerated.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Features2D/FastDetector.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/ICodeGenerable.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Tiff/TileTiffWriter.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/IInterpolatable.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/Platform.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Features2D/Feature2D.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV.Cuda/GpuMatGenerated.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Ocl/Device.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/PInvoke/CvType/MIplImage.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Video/KalmanFilter.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/Toolbox.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Features2D/Features2DInvoke.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/TimedImage.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/PinnedArray.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/TypeEnum.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Features2D/Features2DTracker.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV.Cuda/Imgproc/CudaCannyEdgeDetector.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Ocl/DeviceGenerated.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/Features2D/FlannBasedMatcher.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.Util/UnmanagedObject.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV.Contrib/ImgHash/BlockMeanHash.cs' could not be found.
error CS2001: Source file '/media/microway/CMS\ MB1/falcon/data1/emgucv18/emgucv/Emgu.CV.World/../Emgu.CV/CameraCalibration/Quaternions.cs' could not be found. 

```

**Comment by mauja** [comment]
1) Regarding the location of your makefile, I am seeing something similar under Windows 10. There is supposed to be a solution file in the root directory, but it is not there. Instead it is under a subdirectory called "b". I have opened another issue, regarding this: [https://github.com/emgucv/emgucv/issues/157](url)

2) I did a fresh clone of the emgucv repository, this afternoon. A spot check of the directory tree, shows that your missing files are present, immediately after cloning.

**Comment by mlstudies** [comment]
No I did a fresh clone and the problem persists! 

If you check the Emgu.CV.World folder on github https://github.com/emgucv/emgucv/tree/master/Emgu.CV.World, there is nothing there!! What is wrong?? The compiler is exactly complaining it cannot find these files.

[https://i.stack.imgur.com/R0uNL.png](url)

[https://camo.githubusercontent.com/cca1abef75c8f4d6a899c7312cdc344fa3e6c3e8/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f564a646e642e6a7067](url)

**Comment by mauja** [comment]
Sorry if I am not following, but this is what I have done:

1) Clone the emgucv repository, using the GitHub Desktop application, on Windows 10.
2) Located the first file, in your screenshot (AndroidFileAsset.cs), and confirmed it is there. See my screenshot below.
3) Located the the same file in [https://github.com/emgucv/emgucv/tree/master/Emgu.Util/Android](url)

![emgucv_spot_check](https://user-images.githubusercontent.com/5043383/45026224-abe76e80-b00b-11e8-845d-ce931da2646b.PNG)


![image](https://user-images.githubusercontent.com/5043383/45026314-efda7380-b00b-11e8-8bfa-8ca42f65eaf5.png)

![image](https://user-images.githubusercontent.com/5043383/45026658-fae1d380-b00c-11e8-8df8-c009013a5042.png)

**Comment by emgucv** [comment]
If you are using the master branch, please let us know the commit tag you are using and we will take a look. The development code is constantly changing and Ubuntu compilation may have issues from time to time.

I can confirm that the current master at 0ee48dc can be compiled on Ubuntu 18.04 with no issues.

Please use a tagged release if the master branch cannot be compiled.

FYI, The Emgu.CV.World folder is supposed to be empty. It references the shared projects from Emgu.CV and Emgu.Util folders. The source codes are located in the Emgu.CV and Emgu.Util folder.

**Comment by emgucv** [comment]
Closing ticket now.
